export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILURE = "VERIFY_FAILURE";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILURE = "USER_LIST_FAILURE";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

export const USER_REMOVE_REQUEST = "USER_REMOVE_REQUEST";
export const USER_REMOVE_SUCCESS = "USER_REMOVE_SUCCESS";
export const USER_REMOVE_FAILURE = "USER_REMOVE_FAILURE";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAILURE = "USER_FOLLOW_FAILURE";

export const USER_UNFOLLOW_REQUEST = "USER_UNFOLLOW_REQUEST";
export const USER_UNFOLLOW_SUCCESS = "USER_UNFOLLOW_SUCCESS";
export const USER_UNFOLLOW_FAILURE = "USER_UNFOLLOW_FAILURE";

export const USER_FINDPEOPLE_REQUEST = "USER_FINDPEOPLE_REQUEST";
export const USER_FINDPEOPLE_SUCCESS = "USER_FINDPEOPLE_SUCCESS";
export const USER_FINDPEOPLE_FAILURE = "USER_FINDPEOPLE_FAILURE";

export const NEWSFEED_REQUEST = "NEWSFEED_REQUEST";
export const NEWSFEED_SUCCESS = "NEWSFEED_SUCCESS";
export const NEWSFEED_FAILURE = "NEWSFEED_FAILURE";

export const MYPOSTS_REQUEST = "MYPOSTS_REQUEST";
export const MYPOSTS_SUCCESS = "MYPOSTS_SUCCESS";
export const MYPOSTS_FAILURE = "MYPOSTS_FAILURE";

export const NEWPOST_REQUEST = "NEWPOST_REQUEST";
export const NEWPOST_SUCCESS = "NEWPOST_SUCCESS";
export const NEWPOST_FAILURE = "NEWPOST_FAILURE";

export const GETPOST_REQUEST = "GETPOST_REQUEST";
export const GETPOST_SUCCESS = "GETPOST_SUCCESS";
export const GETPOST_FAILURE = "GETPOST_FAILURE";

export const DELPOST_REQUEST = "DELPOST_REQUEST";
export const DELPOST_SUCCESS = "DELPOST_SUCCESS";
export const DELPOST_FAILURE = "DELPOST_FAILURE";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAILURE = "LIKE_FAILURE";

export const UNLIKE_REQUEST = "UNLIKE_REQUEST";
export const UNLIKE_SUCCESS = "UNLIKE_SUCCESS";
export const UNLIKE_FAILURE = "UNLIKE_FAILURE";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";

export const UNCOMMENT_REQUEST = "UNCOMMENT_REQUEST";
export const UNCOMMENT_SUCCESS = "UNCOMMENT_SUCCESS";
export const UNCOMMENT_FAILURE = "UNCOMMENT_FAILURE";
